apiVersion: v1
data:
  config.yaml: |
    enableUserWorkload: true
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"enableUserWorkload: true\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"cluster-monitoring-config","namespace":"openshift-monitoring"}}
  creationTimestamp: "2026-09-15T14:07:17Z"
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  resourceVersion: "1233837"
  uid: 078e8ada-a1f8-4534-8ba9-72af1705a810
