apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-prod-security
  namespace: mayabank-mq-prod
data:
  security.mqsc: |
    * Production-target MQ objects and least-privilege identities.
    DEFINE QLOCAL('PAYMENT.REQUEST.Q') DEFPSIST(YES) MAXDEPTH(10000) BOQNAME('PAYMENT.BACKOUT.Q') BOTHRESH(3) REPLACE
    DEFINE QLOCAL('PAYMENT.RESPONSE.Q') DEFPSIST(YES) MAXDEPTH(10000) REPLACE
    DEFINE QLOCAL('PAYMENT.BACKOUT.Q') DEFPSIST(YES) MAXDEPTH(10000) REPLACE
    DEFINE QLOCAL('PAYMENT.DLQ') DEFPSIST(YES) MAXDEPTH(10000) REPLACE
    ALTER QMGR DEADQ('PAYMENT.DLQ')

    DEFINE CHANNEL('PAYMENT.ORDER.SVRCONN') CHLTYPE(SVRCONN) SSLCAUTH(REQUIRED) SSLCIPH('ANY_TLS13_OR_HIGHER') REPLACE
    DEFINE CHANNEL('PAYMENT.PROCESSING.SVRCONN') CHLTYPE(SVRCONN) SSLCAUTH(REQUIRED) SSLCIPH('ANY_TLS13_OR_HIGHER') REPLACE

    SET CHLAUTH('PAYMENT.ORDER.SVRCONN') TYPE(SSLPEERMAP) SSLPEER('CN=*') USERSRC(NOACCESS) ACTION(REPLACE)
    SET CHLAUTH('PAYMENT.ORDER.SVRCONN') TYPE(SSLPEERMAP) SSLPEER('CN=payment-order') USERSRC(MAP) MCAUSER('paymentorder') ACTION(REPLACE)
    SET CHLAUTH('PAYMENT.PROCESSING.SVRCONN') TYPE(SSLPEERMAP) SSLPEER('CN=*') USERSRC(NOACCESS) ACTION(REPLACE)
    SET CHLAUTH('PAYMENT.PROCESSING.SVRCONN') TYPE(SSLPEERMAP) SSLPEER('CN=payment-processing') USERSRC(MAP) MCAUSER('paymentproc') ACTION(REPLACE)

    SET AUTHREC PRINCIPAL('paymentorder') OBJTYPE(QMGR) AUTHADD(CONNECT,INQ)
    SET AUTHREC PROFILE('PAYMENT.REQUEST.Q') PRINCIPAL('paymentorder') OBJTYPE(QUEUE) AUTHADD(PUT,INQ)
    SET AUTHREC PROFILE('PAYMENT.RESPONSE.Q') PRINCIPAL('paymentorder') OBJTYPE(QUEUE) AUTHADD(GET,BROWSE,INQ)

    SET AUTHREC PRINCIPAL('paymentproc') OBJTYPE(QMGR) AUTHADD(CONNECT,INQ)
    SET AUTHREC PROFILE('PAYMENT.REQUEST.Q') PRINCIPAL('paymentproc') OBJTYPE(QUEUE) AUTHADD(GET,BROWSE,INQ)
    SET AUTHREC PROFILE('PAYMENT.RESPONSE.Q') PRINCIPAL('paymentproc') OBJTYPE(QUEUE) AUTHADD(PUT,INQ)
    SET AUTHREC PROFILE('PAYMENT.BACKOUT.Q') PRINCIPAL('paymentproc') OBJTYPE(QUEUE) AUTHADD(PUT,INQ)

  security.ini: |
    Service:
        Name=AuthorizationService
        EntryPoints=14
        SecurityPolicy=UserExternal
