apiVersion: v1
kind: Namespace
metadata:
  name: mayabank-mq-build
  labels:
    app.kubernetes.io/part-of: mayabank-mq
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: payments
  namespace: mayabank-mq-build
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: payments
  namespace: mayabank-mq-build
spec:
  runPolicy: Serial
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: payments:0.2.0
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi
  completionDeadlineSeconds: 1200
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
