apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processing
  namespace: mayabank-mq-local
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: payment-processing
  template:
    metadata:
      labels:
        app: payment-processing
        mayabank-role: mq-client
    spec:
      serviceAccountName: payments
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: payments
          image: image-registry.openshift-image-registry.svc:5000/mayabank-mq-build/payments:0.2.0
          imagePullPolicy: Always
          args: [process]
          env:
            - name: MQ_HOST
              value: mq
            - name: MQ_PASSWORD_FILE
              value: /etc/mayabank/mq/mqAppPassword
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          volumeMounts:
            - name: credentials
              mountPath: /etc/mayabank/mq
              readOnly: true
      volumes:
        - name: credentials
          secret:
            secretName: mq-app-credentials
            items:
              - key: mqAppPassword
                path: mqAppPassword
